[package]
name = "konnektoren-platform"
edition = { workspace = true }
version = { workspace = true }
description = "Platform library for Konnektoren"
keywords = ["konnektoren", "platform", "library"]

[features]
default = []
tools = ["regex", "walkdir"]

[dependencies]
isolang = { workspace = true }
konnektoren-core = { path = "../konnektoren-core" }
log = { workspace = true }
regex = { version = "1.11.1", optional = true }
rust-embed = { version = "8.5.0", features = [
    "interpolate-folder-path",
    "debug-embed",
] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
walkdir = { version = "2.5.0", optional = true }

[dev-dependencies]
env_logger = { workspace = true }
mockall = { workspace = true }
