[package]
name = "konnektoren-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = { version = "0.26.2", features = ["serde"] }
konnektoren-core = { path = "../konnektoren-core" }