[package]
name = "konnektoren-core"
version = "0.2.0"
edition = "2021"
description = "Core library for Konnektoren"
license = "MIT"
repository = "https://github.com/Konnektoren/konnektoren-rs"
readme = "../README.md"
authors = ["Christian M <chriamue@gmail.com>"]
keywords = ["konnektoren", "core", "library"]

[lib]
crate-type = ["rlib"]

[features]
default = ["certificates"]
certificates = ["base64", "sha2", "serde_cbor", "ed25519-dalek", "rmp-serde", "image", "imageproc", "ab_glyph", "plot_icon", "qrcode"]
js = ["wasm-bindgen", "wasm-bindgen-futures", "web-sys", "js-sys"]

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4.38", features = ["serde"] }
log = { version = "0.4" }
names = { version = "0.15.0-dev", git="https://github.com/jakswa/names", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.33"
# certificate features
base64 = { version = "0.22.1", optional = true }
sha2 = { version = "0.10.8", optional = true }
serde_cbor = { version = "0.11.2", optional = true }
ed25519-dalek = { version = "2.1.1", default-features = false, optional = true }
rmp-serde = { version = "1.1.2", optional = true }
image = { version = "0.25.1", optional = true }
imageproc = { version = "0.25", optional = true }
ab_glyph = { version = "0.2.28", optional = true }
plot_icon = { version = "0.3.0", optional = true }
qrcode = { version = "0.14.1", optional = true }
# js features
wasm-bindgen = { version = "0.2.93", optional = true }
wasm-bindgen-futures = { version = "0.4.43", optional = true }
web-sys = { version = "0.3.70", optional = true }
js-sys = { version = "0.3.70", optional = true }
