[package]
name = "konnektoren-yew"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "konnektoren-yew-bin"
path = "src/main.rs"

[dependencies]
console_log = "1.0"
implicit-clone = "0.4.9"
indexmap = "2.2.6"
wasm-bindgen = { version = "0.2", features = ["serde"] }
yew = { version = "0.21", features = ["csr"] }

konnektoren-core = { path = "../konnektoren-core" }
log = "0.4.21"
