name: GitHub Pages and Asciidoc PDF Build

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build_adoc_pdf:
    name: Build Asciidoc to PDF with PlantUML
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install Asciidoctor, Asciidoctor PDF, and Asciidoctor Diagram (for PlantUML support)
      - name: Install Asciidoctor and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor graphviz default-jre
          sudo gem install asciidoctor-pdf --pre
          sudo gem install asciidoctor-diagram

      # Convert Asciidoc to PDF with PlantUML support
      - name: Build PDF from Asciidoc
        run: |
          asciidoctor-pdf -r asciidoctor-diagram -o output/documentation.pdf docs/README.adoc

      # Upload the PDF as an artifact
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Documentation PDF
          path: output/documentation.pdf
          overwrite: 'true'
