name: GitHub Pages and Asciidoc PDF Build

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build_adoc_pdf:
    name: Build Asciidoc to PDF with PlantUML
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install Asciidoctor, Asciidoctor PDF, PlantUML and dependencies
      - name: Install Asciidoctor and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor graphviz default-jre plantuml
          sudo gem install asciidoctor-pdf --pre
          sudo gem install asciidoctor-diagram

      # Download PlantUML JAR
      - name: Download PlantUML JAR
        run: |
          wget https://github.com/plantuml/plantuml/releases/download/v1.2025.4/plantuml-1.2025.4.jar -O plantuml.jar

      # Create output directory
      - name: Create output directory
        run: |
          mkdir -p output

      # Build PDF from Asciidoc
      - name: Build PDF from Asciidoc
        env:
          DIAGRAM_PLANTUML_CLASSPATH: ${{ github.workspace }}/plantuml.jar
        run: |
          asciidoctor-pdf -r asciidoctor-diagram \
            -o output/documentation.pdf \
            -a sourcedir=docs/src \
            -a imagesdir=images \
            -a diagramsdir=diagrams \
            docs/README.adoc

      # Upload the PDF as an artifact
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Documentation PDF
          path: output/documentation.pdf
          overwrite: "true"

  deploy_pages:
    name: Deploy GitHub Pages
    runs-on: ubuntu-22.04
    needs: build_adoc_pdf
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install Asciidoctor, PlantUML and dependencies
      - name: Install Asciidoctor and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor graphviz default-jre plantuml
          sudo gem install asciidoctor-diagram

      # Download PlantUML JAR
      - name: Download PlantUML JAR
        run: |
          wget https://github.com/plantuml/plantuml/releases/download/v1.2025.4/plantuml-1.2025.4.jar -O plantuml.jar

      # Create output directory
      - name: Create output directory
        run: |
          mkdir -p output/docs

      # Build HTML from Asciidoc
      - name: Build HTML from Asciidoc
        env:
          DIAGRAM_PLANTUML_CLASSPATH: ${{ github.workspace }}/plantuml.jar
        run: |
          asciidoctor -r asciidoctor-diagram \
            -D output/docs \
            -a imagesdir=images \
            -a diagramsdir=diagrams \
            -a sourcedir=docs/src \
            -a toc=left \
            -a toclevels=3 \
            -a sectanchors \
            -a source-highlighter=highlightjs \
            docs/README.adoc

      # Copy images directory to output/docs
      - name: Copy Images
        run: |
          cp -r docs/images output/docs/ || true

      # Copy diagrams directory to output/docs
      - name: Copy Diagrams
        run: |
          cp -r docs/diagrams output/docs/ || true

      # Copy index.html
      - name: Copy index.html
        run: |
          cp output/docs/README.html output/docs/index.html

      # Deploy to GitHub Pages (to docs/ subdir)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          keep_files: true
